server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: CTSC Work Allocation
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/workallocation
    username: workallocation
    password: workallocation
    properties:
      charSet: UTF-8
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
idam:
  s2s-auth:
    totp_secret: ${S2S_SECRET:ABCD1F2BABCD1F2B}
    microservice: ctsc_work_allocation
    url: ${S2S_AUTH_URL:http://localhost:23443}
    redirect_uri: /oauth2/callback
  service-user:
    email: ${SERVICE_USER_EMAIL:service.user@mail.com}
    password: ${SERVICE_USER_PASSWORD:password123}

auth:
  idam:
    client:
      baseUrl: ${IDAM_CLIENT_BASE_URL:http://localhost:23443}
ccd:
  baseUrl: ${CCD_API_URL:http://localhost:23443}
  ctids: DIVORCE

server-url: ${SERVER_URL:http://localhost:8080}
last-run-log: ${LAST_RUN_LOG:./last_run.log}

http:
  client:
    timeout: 5

service:
  email: 'ctsc.workallocation.service@hmcts.net'

smtp:
  host: 'smtp.office365.com'
  port: 587
  user: 'ctsc-email-channel@HMCTS.NET'
  password: 'London123'
  from: 'hmcts@hmcts.dcbp.co.uk'
