server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: CTSC Work Allocation
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true
idam:
  s2s-auth:
    totp_secret: ${S2S_SECRET:ABCD1F2BABCD1F2B}
    microservice: ctsc_work_allocation
    url: ${S2S_AUTH_URL:http://localhost:23443}
  service-user:
    email: ${SERVICE_USER_EMAIL:service.user@mail.com}
    password: ${SERVICE_USER_PASSWORD:password123}

auth:
  idam:
    client:
      baseUrl: ${IDAM_CLIENT_BASE_URL:http://localhost:23443}
http:
  client:
    timeout: 5
